### ISSUE TITLE
ERROR: No matching distribution found for pytorch-accelerated

### ISSUE THREAD

**Issue by phosseini** [Chris-hughes10/pytorch-accelerated#18]
I'm just trying to install the package using the pip command and I get the following errors:
```
ERROR: Could not find a version that satisfies the requirement pytorch-accelerated (from versions: none)
ERROR: No matching distribution found for pytorch-accelerated
```
Am I missing something?

P.S. I've already installed the requirements including `accelerate` and `tqdm`

**Comment by Chris-hughes10** [comment]
Hi @phosseini, I am struggling to replicate your issue. What versions of Python and pip are you using?

**Comment by phosseini** [comment]
> Hi @phosseini, I am struggling to replicate your issue. What versions of Python and pip are you using?

`Python 3.6.13 :: Anaconda, Inc.`
`pip 21.3.1`

I installed it successfully on Google Colab, so could it be because of Python 3.6?

**Comment by Chris-hughes10** [comment]
Aha, yes that is the reason, `pytorch-accelerated` only supports Python 3.7 and above! I'd suggest creating a new env and trying again.

**Comment by phosseini** [comment]
I see, thanks. Would be nice if you add it to the documentation.
