### ISSUE TITLE
Do we need to set mixed-precision explicitly or is it handled if tensor cores available? 

### ISSUE THREAD

**Issue by sayakpaul** [Chris-hughes10/pytorch-accelerated#19]
I following your awesome guide on `timm`: https://towardsdatascience.com/getting-started-with-pytorch-image-models-timm-a-practitioners-guide-4e77b4bf9055. 

I am running training on an A100-based VM which should support mixed-precision training. Does `Trainer` from PyTorch Accelerated take care of that automatically?

**Comment by Chris-hughes10** [comment]
Hi, thank you for the kind words! The `Trainer` will handle mixed precision for you, so there will be no changes needed to your code, as long as it is set in your accelerate config when launching training.

As described [here](https://pytorch-accelerated.readthedocs.io/en/latest/quickstart.html), you can create a config file using the command `accelerate config --config_file accelerate_config.yaml`. You can verify that mixed precision is set by inspecting the config file which, depending on your answers, should look something like this:

![image](https://user-images.githubusercontent.com/31883449/158577834-8c1f0df6-04ec-4269-b6a5-3e8f65db4a47.png)

If you then launch with that config, using:
`accelerate launch --config_file accelerate_config.yaml train.py [--training-args]`

mixed precision will be enabled!

**Comment by sayakpaul** [comment]
Thank you!

I am using a similar `main.py` script as yours (shown in your tutorial) so I assume there won't be a need to launch with config file or am I mistaken?

**Comment by Chris-hughes10** [comment]
Hi, if you launch without a config file, it will assume default settings, which will use 1GPU and mixed precision will be disabled. 

The idea behind the config file and the accelerate cli is that you have a consistent launch command regardless of your infrastructure; you don't need to bother with `python -m torch.distributed ..` and all of that stuff. If you want to use multiple GPUs, or toggle fp16, then all you need to do is update that file, and not the code. Of course, launching without the accelerate CLI will still work, but you will need to make some code changes to enable mixed precision. 

Personally, I would recommend always launching with `accelerate launch` and the config file, as it offers the most flexibility with the least amount of effort.

**Comment by sayakpaul** [comment]
Thanks for clarifying, that helps. 

> Of course, launching without the accelerate CLI will still work, but you will need to make some code changes to enable mixed precision.

Could you also hint at how those changes might look like? It's good to also be aware of that I think.

**Comment by sayakpaul** [comment]
Thanks so much for being thorough with your explanations. And yes it makes sense to use config files to launch training whenever possible.
