### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ross-Hr** [Chris-hughes10/pytorch-accelerated#56]
Hi, i am a beginner.

  May I ask how to convert the code into distributed training ?  The error looks like :
 `
File "/data/code/Yolov7-training/yolov7/trainer.py", line 132, in calculate_eval_batch_loss
    preds = self.model.postprocess(fpn_heads_outputs, conf_thres=0.001)
  File "/home/xiaoxiong/anaconda3/envs/yolov7/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'postprocess'
`
I also can not find the template code.

**Comment by Chris-hughes10** [comment]
Hi,

There shouldn't need to be any changes to the code for distributed training, you just need to update the accelerate config as detailed (here)[https://pytorch-accelerated.readthedocs.io/en/latest/quickstart.html].

That error looks specific to Yolo7, so I will close this issue here
