### ISSUE TITLE
Distributed training results in slow convergence

### ISSUE THREAD

**Issue by biewubwerqwe** [Chris-hughes10/pytorch-accelerated#59]
Hi,
I am using the sample code for [timm model training](https://github.com/Chris-hughes10/pytorch-accelerated/blob/main/examples/vision/using_timm_components/all_timm_components.py). There is a mismatch when am accelerating the code with GPU and otherwise. What can be the reason for this

![image](https://github.com/Chris-hughes10/pytorch-accelerated/assets/164993131/c73f0d80-44d6-4aca-9f76-e164a0d2f167)

There are 3 results in the image

1. `baseline_batch-32` is the values by just doing `python train.py`
2. `baseline_batch-32_nodist` is the results of using accelerate config `accelerate_config_nodist.yaml
3. `baseline_batch-32_1gpu is the results of using accelerate config `accelerate_config_1gpu.yaml`

The config for nodist is
`compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: '1'
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
`

The config for 1 gpu is
`compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 3,
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false`

**Comment by Chris-hughes10** [comment]
Hi, what is the difference between your configs, they look the same to me?

**Comment by biewubwerqwe** [comment]
Sorry, that was a mistake. I pasted same config twice. I have corrected now and you can see the differnce
