### ISSUE TITLE
`wandblogger`?

### ISSUE THREAD

**Issue by deven367** [Chris-hughes10/pytorch-accelerated#61]
Thanks for this amazing library @Chris-hughes10! Is there a plan for `wandblogger` in the near future for the library?

**Comment by Chris-hughes10** [comment]
There are no plans to offer this built-in. It should be pretty easy to create a custom callback for this though, as described here: https://pytorch-accelerated.readthedocs.io/en/latest/callbacks.html#example-create-a-custom-logging-callback
